#!/bin/bash

entropy-decomposition clone43-v6v4.fa -A 1 -m 0.2 --number-of-discriminants 3 --output test-decomposition-output
python ../../Oligotyping/visualization/decomposition_topology.py test-decomposition-output/TOPOLOGY.txt 
python ../../Oligotyping/visualization/oligotype_distribution_stack_bar.py test-decomposition-output/ENVIRONMENT.txt
rm -rf test-decomposition-output
