#!/bin/bash

set -e

decompose clone43-v6v4.fa -M 1 -m 0.2 --number-of-discriminants 3 --output `pwd`/test-decomposition-output -F --skip-check-input
python ../../Oligotyping/visualization/oligotype_distribution_stack_bar.py test-decomposition-output/ENVIRONMENT.txt --output-file test-decomposition-output/ENVIRONMENT.png
python ../../Oligotyping/visualization/decomposition_topology.py test-decomposition-output/TOPOLOGY-LIGHT.cPickle
#rm -rf test-decomposition-output
